interface HttpCode {
    [key: number]: string;
}

const http_code: HttpCode = {
    100: 'Continuar',
    101: 'Mudando Protocolos',
    102: 'Processando',
    200: 'Sucesso',
    201: 'Criado',
    202: 'Aceito',
    203: 'Informação Não Confiável',
    204: 'Sem Conteúdo',
    205: 'Resetar Conteúdo',
    206: 'Conteúdo Parcial',
    207: 'Multi-Status',
    300: 'Múltiplas Escolhas',
    301: 'Movido Permanentemente',
    302: 'Encontrado',
    303: 'Ver Outro',
    304: 'Não Modificado',
    305: 'Usar Proxy',
    307: 'Redirecionamento Temporário',
    400: 'Requisição Inválida',
    401: 'Não Autorizado',
    402: 'Pagamento Necessário',
    403: 'Proibido',
    404: 'Não Encontrado',
    405: 'Método Não Permitido',
    406: 'Não Aceitável',
    407: 'Autenticação de Proxy Necessária',
    408: 'Tempo de Requisição Esgotado',
    409: 'Conflito',
    410: 'Removido',
    411: 'Comprimento Necessário',
    412: 'Pré-condição Falhou',
    413: 'Carga Muito Grande',
    414: 'URI Muito Longa',
    415: 'Tipo de Mídia Não Suportado',
    416: 'Faixa Não Satisfatória',
    417: 'Expectativa Falhou',
    418: 'Sou um bule de chá',
    421: 'Requisição Redirecionada',
    422: 'Entidade Não Processável',
    423: 'Bloqueado',
    424: 'Dependência Falhou',
    425: 'Muito Cedo',
    426: 'Atualização Necessária',
    428: 'Pré-condição Necessária',
    429: 'Muitas Requisições',
    431: 'Cabeçalhos de Requisição Muito Grandes',
    451: 'Indisponível por Motivos Legais',
    500: 'Erro Interno do Servidor',
    501: 'Não Implementado',
    502: 'Gateway Inválido',
    503: 'Serviço Indisponível',
    504: 'Tempo de Gateway Esgotado',
    505: 'Versão HTTP Não Suportada',
    506: 'Variante Também Negocia',
    507: 'Armazenamento Insuficiente',
    508: 'Loop Detectado',
    510: 'Não Estendido',
    511: 'Autenticação de Rede Necessária'
};

export default http_code;